services:
  #Node Container
  node:
    image: node:lts
    container_name: aprove-me-node
    tty: true
    user: "node:node"
    working_dir: /var/www
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./:/var/www
    networks:
      - app-network
    environment:
      HOST: 0.0.0.0
  
  sqlite3:
    image: nouchka/sqlite3:latest
    container_name: aprove-me-sqlite
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
